# Site settings
title: Talita Shiguemoto
email: talita.shiguemoto@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl: https://shiguelita.github.io
url:  # the base hostname & protocol for your site
twitter_username: twitter_shiguelita
github_username:  github_shiguelita

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/home/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: false
    permalink: /poetry/:path/


