# Site settings
title: Talita Shiguemoto
email: talita.shiguemoto@gmail.com
description:
  en: Some of my thoughts and analysis about my interests in data science, machine learning and artificial intelligence
  pt: Alguns dos meus pensamentos e análises sobre meus interesses em ciência de dados, aprendizado de máquina e inteligência artificial
index: 
  en:
  pt: index_pt.html

# Link settings
baseurl: ""
url: "https://shiguelita.github.io"

# Social settings
social_sites:
  #twitter: jekyllrb
  github:  shiguelita
  #dribbble: jekyll
  #facebook: jekyll
  #flickr: jekyll
  instagram: shiguelita
  linkedin: talitashiguemoto
  #pinterest: jekyll
  #youtube: jekyll
  #googleplus: +jekyll

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/home/page:num/"

# Disqus
disqus_shortname: shiguelita

# Google analytics
google_analytics: UA-121973887-1

collections:
  projects:
    output: true
    permalink: /projects/:path/
  posts:
    output: true
    permalink: /posts/:path/

t:
  en:
    home:
      name: "home"
      url: "/"
    projects:
      name: "projects"
      url: "/projects/"
    posts:
      name: "notebook"
      url: "/notebook/"
  pt:
    home:
      name: "home"
      url: "/index_pt.html"
    projects:
      name: "projetos"
      url: "/projects_pt/"
    posts:
      name: "anotações"
      url: "/notebook_pt/"


