# Site settings
title: Talita Shiguemoto
email: talita.shiguemoto@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl: 
url:  https://shiguelita.github.io
twitter_username: 
github_username:  shiguelita

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/home/page:num/"

# Disqus
disqus:
  shortname: shiguelita


collections:
  projects:
    output: true
    permalink: /projects/:path/
  notebook:
    output: true
    permalink: /notebook/:path/


