# Site settings
title: Talita Shiguemoto
email: talita.shiguemoto@gmail.com
index: 
  en:
  pt: index_pt.html

# Link settings
baseurl: ""
url: "https://shiguelita.github.io"

# Social settings
social_sites:
  #twitter: jekyllrb
  github:  shiguelita
  #dribbble: jekyll
  #facebook: jekyll
  #flickr: jekyll
  instagram: shiguelita
  linkedin: talitashiguemoto
  #pinterest: jekyll
  #youtube: jekyll
  #googleplus: +jekyll

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/home/page:num/"

# Disqus
disqus_shortname: shiguelita

# Google analytics
google_analytics: UA-121973887-1

t:
  en:
    home:
      name: "home"
      url: "/"
    projects:
      name: "projects"
      url: "/projects/"
    notebook:
      name: "notebook"
      url: "/notebook/"
  pt:
    home:
      name: "home"
      url: "/index_pt/"
    projects:
      name: "projetos"
      url: "/projects_pt/"
    notebook:
      name: "anotações"
      url: "/notebook_pt/"




